# Generated by Django 5.2.3 on 2025-06-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestioneLaboratoriUniversitari', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilo',
            name='matricola',
            field=models.CharField(default='P00000', max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
