# Generated by Django 5.2.3 on 2025-06-19 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenotazionelaboratorio',
            name='professore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.professore'),
        ),
        migrations.AlterUniqueTogether(
            name='prenotazionelaboratorio',
            unique_together={('laboratorio', 'data', 'ora_inizio', 'ora_fine')},
        ),
    ]
