# Generated by Django 5.2.3 on 2025-06-19 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_alter_prenotazionelaboratorio_professore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenotazioneattrezzatura',
            name='professore',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sistema.professore'),
        ),
        migrations.AlterField(
            model_name='professore',
            name='utente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sistema.utente'),
        ),
    ]
