# Generated by Django 5.2.3 on 2025-06-20 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_alter_prenotazioneattrezzatura_professore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenotazioneattrezzatura',
            name='professore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.professore'),
        ),
        migrations.AlterField(
            model_name='prenotazionelaboratorio',
            name='esperimento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sistema.esperimento'),
        ),
        migrations.AlterField(
            model_name='utente',
            name='matricola',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
